"""init

Revision ID: 602b80d7fdc7
Revises: 
Create Date: 2026-04-21 13:42:26.191906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '602b80d7fdc7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('total_tests_count', sa.Integer(), nullable=False),
    sa.Column('passed_tests_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PASSED', 'FAILED', 'ERROR', name='evaluationstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_submission_id'), 'evaluations', ['submission_id'], unique=False)
    op.create_table('input_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('input_data', sa.String(length=500), nullable=False),
    sa.Column('expected_output', sa.String(length=500), nullable=False),
    sa.Column('check_type', sa.Enum('EXACT_MATCH', 'IGNORE_WHITESPACE', 'LINE_BY_LINE', 'FLOAT_COMPARE', name='checktype', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_input_cases_assignment_id'), 'input_cases', ['assignment_id'], unique=False)
    op.create_table('outbox_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PUBLISHED', 'PROCESSING', 'FAILED', name='outboxstatus', native_enum=False), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('input_data', sa.String(length=500), nullable=False),
    sa.Column('expected_output', sa.String(length=500), nullable=False),
    sa.Column('check_type', sa.Enum('EXACT_MATCH', 'IGNORE_WHITESPACE', 'LINE_BY_LINE', 'FLOAT_COMPARE', name='checktype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PASSED', 'WRONG_ANSWER', 'RUNTIME_ERROR', 'TIMEOUT', 'MEMORY_LIMIT', 'SYSTEM_ERROR', name='executionstatus', native_enum=False), nullable=True),
    sa.Column('stdout', sa.String(length=500), nullable=True),
    sa.Column('stderr', sa.String(length=500), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_cases_evaluation_id'), 'execution_cases', ['evaluation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_cases_evaluation_id'), table_name='execution_cases')
    op.drop_table('execution_cases')
    op.drop_table('outbox_messages')
    op.drop_index(op.f('ix_input_cases_assignment_id'), table_name='input_cases')
    op.drop_table('input_cases')
    op.drop_index(op.f('ix_evaluations_submission_id'), table_name='evaluations')
    op.drop_table('evaluations')
    # ### end Alembic commands ###
