from uuid import UUID
from typing import Protocol

from checking_service.application.models.outbox import OutboxMessage


class OutboxRepository(Protocol):
    async def add(self, message: OutboxMessage) -> None: ...
    async def claim_batch(self, limit: int) -> list[OutboxMessage]: ...
    async def mark_published(self, id: UUID) -> None: ...
    async def mark_failed(self, id: UUID) -> None: ...
