FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /runtime

COPY docker/shared /runtime/shared
COPY docker/images/csharp /runtime/csharp

ENV PYTHONPATH=/runtime

RUN apt-get update && \
    apt-get install -y python3 && \
    rm -rf /var/lib/apt/lists/*

RUN useradd -m runner

RUN mkdir /workspace && \
    chown runner:runner /workspace

USER runner

CMD ["sleep", "infinity"]