"""init

Revision ID: b1dbbbb0f24b
Revises:
Create Date: 2026-05-09 00:25:16.666740

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b1dbbbb0f24b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assignments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "final_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("group_assignment_id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("submission_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("tests_total", sa.Integer(), nullable=False),
        sa.Column("tests_passed", sa.Integer(), nullable=False),
        sa.Column("plagiarism_score", sa.Float(precision=3), nullable=False),
        sa.Column("plagiarism_flag", sa.Boolean(), nullable=False),
        sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "group_assignment_id",
            "student_id",
            name="uq_final_result_group_assignment_student",
        ),
    )
    op.create_index(
        op.f("ix_final_results_group_assignment_id"),
        "final_results",
        ["group_assignment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_final_results_student_id"),
        "final_results",
        ["student_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_final_results_submission_id"),
        "final_results",
        ["submission_id"],
        unique=False,
    )
    op.create_table(
        "group_assignments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("assignment_id", sa.UUID(), nullable=False),
        sa.Column(
            "allowed_languages",
            postgresql.ARRAY(
                sa.Enum("PYTHON", "CSHARP", name="language", native_enum=False)
            ),
            nullable=False,
        ),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "FINALIZING",
                "FINALIZED",
                name="groupassignmentstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_group_assignments_status"),
        "group_assignments",
        ["status"],
        unique=False,
    )
    op.create_table(
        "outbox_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=255), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "submissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("assignment_id", sa.UUID(), nullable=False),
        sa.Column("group_assignment_id", sa.UUID(), nullable=False),
        sa.Column(
            "language",
            sa.Enum("PYTHON", "CSHARP", name="language", native_enum=False),
            nullable=False,
        ),
        sa.Column("code", sa.String(length=5000), nullable=False),
        sa.Column("code_hash", sa.String(length=128), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "IN_PROGRESS",
                "COMPLETED",
                "FAILED",
                name="submissionstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("tests_passed", sa.Integer(), nullable=True),
        sa.Column("tests_total", sa.Integer(), nullable=True),
        sa.Column("evaluation_id", sa.UUID(), nullable=True),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "student_id", "code_hash", name="uq_submission_student_code_hash"
        ),
        sa.UniqueConstraint(
            "student_id",
            "group_assignment_id",
            "attempt_number",
            name="uq_submission_attempt",
        ),
    )
    op.create_index(
        "idx_submission_student_assignment_attempt",
        "submissions",
        ["student_id", "group_assignment_id", "attempt_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_submissions_assignment_id"),
        "submissions",
        ["assignment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_submissions_evaluation_id"),
        "submissions",
        ["evaluation_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_submissions_group_assignment_id"),
        "submissions",
        ["group_assignment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_submissions_status"), "submissions", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_submissions_status"), table_name="submissions")
    op.drop_index(op.f("ix_submissions_group_assignment_id"), table_name="submissions")
    op.drop_index(op.f("ix_submissions_evaluation_id"), table_name="submissions")
    op.drop_index(op.f("ix_submissions_assignment_id"), table_name="submissions")
    op.drop_index("idx_submission_student_assignment_attempt", table_name="submissions")
    op.drop_table("submissions")
    op.drop_table("outbox_messages")
    op.drop_index(op.f("ix_group_assignments_status"), table_name="group_assignments")
    op.drop_table("group_assignments")
    op.drop_index(op.f("ix_final_results_submission_id"), table_name="final_results")
    op.drop_index(op.f("ix_final_results_student_id"), table_name="final_results")
    op.drop_index(
        op.f("ix_final_results_group_assignment_id"), table_name="final_results"
    )
    op.drop_table("final_results")
    op.drop_table("assignments")
    # ### end Alembic commands ###
