"""init

Revision ID: e571dd983329
Revises: 
Create Date: 2026-05-14 19:21:03.016555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e571dd983329'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('tests_total', sa.Integer(), nullable=False),
    sa.Column('tests_passed', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PASSED', 'FAILED', 'MEMORY_EXCEEDED', 'ERROR', 'SYSTEM_ERROR', name='evaluationstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_submission_id'), 'evaluations', ['submission_id'], unique=False)
    op.create_table('test_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('input_data', sa.String(length=500), nullable=False),
    sa.Column('expected_output', sa.String(length=500), nullable=False),
    sa.Column('check_type', sa.Enum('EXACT_MATCH', 'IGNORE_WHITESPACE', 'LINE_BY_LINE', 'FLOAT_COMPARE', name='checktype', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cases_assignment_id'), 'test_cases', ['assignment_id'], unique=False)
    op.create_table('execution_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('input_data', sa.String(length=500), nullable=False),
    sa.Column('expected_output', sa.String(length=500), nullable=False),
    sa.Column('check_type', sa.Enum('EXACT_MATCH', 'IGNORE_WHITESPACE', 'LINE_BY_LINE', 'FLOAT_COMPARE', name='checktype', native_enum=False), nullable=False),
    sa.Column('stdout', sa.String(length=500), nullable=False),
    sa.Column('stderr', sa.String(length=500), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_cases_evaluation_id'), 'execution_cases', ['evaluation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_cases_evaluation_id'), table_name='execution_cases')
    op.drop_table('execution_cases')
    op.drop_index(op.f('ix_test_cases_assignment_id'), table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index(op.f('ix_evaluations_submission_id'), table_name='evaluations')
    op.drop_table('evaluations')
    # ### end Alembic commands ###
