from typing import Protocol


class UnitOfWork(Protocol):
    ...

    async def __aenter__(self): ...
    async def __aexit__(self): ...
    async def commit(self): ...
    async def rollback(self): ...
