FROM python:3.13-slim AS base

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    postgresql-client \
    curl \
    && rm -rf /var/lib/apt/lists/*


RUN pip install uv


FROM base AS builder

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen

FROM base AS runtime

COPY --from=builder /app/.venv /app/.venv

ENV PATH="/app/.venv/bin:$PATH"
ENV PYTHONPATH="/app/src"

COPY src ./src
COPY alembic ./alembic
COPY alembic.ini .
COPY .env .
COPY docker ./docker

RUN chmod +x docker/*.sh

ENTRYPOINT ["./docker/entrypoint.sh"]

CMD ["uvicorn", "checking_service.main:app", "--host", "0.0.0.0", "--port", "8000"]